# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('player', models.CharField(max_length=32)),
                ('race', models.CharField(choices=[('light', 'Peuple de la Lumière'), ('shadow', "Peuple de l'Ombre"), ('water', "Peuple de l'Eau"), ('fire', 'Peuple du Feu'), ('earth', 'Peuple de la Terre'), ('air', "Peuple de l'Air")], max_length=32)),
                ('level', models.IntegerField()),
                ('str', models.IntegerField()),
                ('dex', models.IntegerField()),
                ('agi', models.IntegerField()),
                ('vig', models.IntegerField()),
                ('vit', models.IntegerField()),
                ('int', models.IntegerField()),
                ('per', models.IntegerField()),
                ('cha', models.IntegerField()),
                ('wil', models.IntegerField()),
                ('mem', models.IntegerField()),
            ],
        ),
    ]
